services:
  django_db:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: postgres
    ports:
      - 5432:5432
    networks:
      - django_network

  django_pgadmin:
    image: dpage/pgadmin4
    container_name: ${COMPOSE_PROJECT_NAME}-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USERNAME}@${DB_USERNAME}.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_USERNAME}
      MASTER_PASSWORD_REQUIRED: False
    ports:
      - 8080:80
    networks:
      - django_network
    depends_on:
      - django_db

  django_web:
    container_name: ${COMPOSE_PROJECT_NAME}-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_NAME: ${DB_DATABASE}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_PORT: ${DB_PORT}
    depends_on:
      - django_db
    networks:
      - django_network

networks:
  django_network:
    driver: bridge
