version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: postgres
    ports:
      - "5432:5432"
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USERNAME}@${DB_USERNAME}.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_USERNAME}
      MASTER_PASSWORD_REQUIRED: False
    ports:
      - "8080:80"
    networks:
      - network
    links:
      - db:${DB_HOST}

  web:
    container_name: ${COMPOSE_PROJECT_NAME}-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_NAME: ${DB_DATABASE}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_PORT: ${DB_PORT}
    links:
      - db:${DB_HOST}
    networks:
      - network

networks:
  network:
    driver: bridge
